### ISSUE TITLE
Mobile Versions

### ISSUE THREAD

**Issue by thecoder08** [KuromeSan/KitsuneOffline#2]
Cool project, good way to practice bundling an NW.js app. I made a build script to automagically build NW.js apps from the code, and used it to make the Linux, MacOS, Debian+derivatives (Ubuntu, Pop!_OS, etc), and Windows versions, for your convenience. I just cloned the github repo, ran a command, and BOOM! They are available for download [here](https://drive.google.com/file/d/1dtJOPSw3nFyg6csxAPLtPR6-30fzmuu0/view?usp=sharing) (1.1 GB .zip), on my Google Drive. You can create a new release and upload the contents of the .zip to make the app cross-platform.

**Comment by LiEnby** [comment]
nice, i would like to make an android version of this at some point too, you can do it using WebViews from what i understand, you can probably do it on iOS too..

**Comment by LiEnby** [comment]
also, how do you get the mp4 videos to play on linux ?

**Comment by thecoder08** [comment]
Yeah it’s definitely possible to make it into a mobile app using WebViews, in fact, that’s exactly what the Cordova Framework does automatically. It’s basically NW.js, but mobile! (and no node.js integration) You pass it your HTML/JS/CSS and it gives you an app (.apk for android, .ipa for iOS). The only issue is that you’ll have to get an Apple developer membership ($100 a month) to get it on the App Store or pay $5 to get it on the Google Play Store. It might be easier to put the apps up for download on the releases page, and let users sideload them. (Also if they are on iOS they will have to either self-sign them as Apple doesn’t allow running unsigned code, or jailbreak their phone)

You question about the mp4s. ffmpeg is integrated with NW.js and it works fine to play the video cutscenes for me.

**Comment by thecoder08** [comment]
In fact, I’m going to make an iOS version right now. The web page should detect that it’s mobile because Cordova has the same user agent as Safari.

**Comment by LiEnby** [comment]
i have a google play developer acocunt i can try submitting it, its unknown if google would approve what is effectively just a rip off of one of there games though

**Comment by thecoder08** [comment]
That’s true. There’s probably some sort of copyright or something that will prevent us from publishing it.

**Comment by LiEnby** [comment]
we could get around that by programming the google play one to instead download the files from rc6 on google servers first.. maybe/

**Comment by thecoder08** [comment]
Maybe, but usually copyright is about the end product, what ends up on the screen, rather than about how it gets there. After all The end user doesn’t know (or care) how their game gets displayed. So even if we do make it download the code, it’s still Google’s game. Also, the whole point of this is to make the game offline and if we’re downloading the code, we’re relying on the user being connected to the internet when they open the app.

**Comment by LiEnby** [comment]
hm true. i was thinking more like it downloads it once then never again kinda thing, but whatever, 

Google Play also allows emulators, and that minecraft java launcher, so maybe? this is fine

**Comment by LiEnby** [comment]
Alright i added an APK ;;

**Comment by thecoder08** [comment]
hmm, i've encountered an issue in making the iOS app. It seems that all of the filepaths of files referencing each other (e.g. kitsune20.html to kitsune20.js) are absolute, and they don't want to work with cordova as your app is not the root. I have attempted to change them with Find+Replace, but I was unsuccessful. Any ideas?

**Comment by thecoder08** [comment]
also, could you upload the .deb that I provided? It would be nice to have it for Linux distributions that are based on Debian (or Debian itself) so that you don't have to extract, create shortcut, etc, and instead just one-click install.

**Comment by LiEnby** [comment]
> hmm, i've encountered an issue in making the iOS app. It seems that all of the filepaths of files referencing each other (e.g. kitsune20.html to kitsune20.js) are absolute, and they don't want to work with cordova as your app is not the root. I have attempted to change them with Find+Replace, but I was unsuccessful. Any ideas?

i ran into a simular issue w the android port i did, the solution i found was to do this: https://github.com/KuromeSan/KitsuneOffline/blob/master/app/src/webview/java/com/silica/kitsune/WebPlayerView.java#L102

also, i really dont like the idea of modifying the original javascript files >_<

**Comment by thecoder08** [comment]
that link seems to be broken :(

**Comment by LiEnby** [comment]
sorry thats https://github.com/KuromeSan/KitsuneOffline/blob/android/app/src/webview/java/com/silica/kitsune/WebPlayerView.java#L102

**Comment by thecoder08** [comment]
changed the title because thats what we're talking about now

**Comment by thecoder08** [comment]
@KuromeSan iOS version is finished! Can you create a new branch called `ios` that I can PR my changes too? Also: It is configured to use GitHub actions as well.

**Comment by thecoder08** [comment]
However the new Actions config will need to be in a separate PR, which I will make after you create the `ios` branch

**Comment by LiEnby** [comment]
k done

**Comment by thecoder08** [comment]
Actually I can’t pr to it as they have different histories. Can you delete the branch and run these commands? They just clone my fork, select my ios branch, add this repository as a remote, and push the ios branch to it
```
git clone https://github.com/thecoder08/KitsuneOffline.git
cd KitsuneOffline
git checkout ios
git remote add upstream https://github.com/KuromeSan/KitsuneOffline.git
git push upstream ios
```

**Comment by LiEnby** [comment]
ok done,

**Comment by thecoder08** [comment]
@KuromeSan Ok, Pull Request for Github Actions has been made. Just merge it now.

**Comment by thecoder08** [comment]
Also: Could you give me a list of commands that you use to build the android app? What platform do you build it on? I should be able to set Actions up to build it automatically too

**Comment by LiEnby** [comment]
I just used android studio dont really know the commands.

**Comment by thecoder08** [comment]
@KuromeSan OK. I looked it up and the command you use to build an android app (that Android Studio runs under the hood) is `./gradlew build`. `gradlew` is a file in your project. OK, I'll set it up.

**Comment by thecoder08** [comment]
Hmm, I seem to be getting this error when building:
```
> Task :app:processZz_crosswalkDebugResources
/home/runner/work/KitsuneOffline/KitsuneOffline/app/src/main/java/com/silica/kitsune/WebPlayerActivity.java:125: error: Bootstrapper is not abstract and does not override abstract method onPrepare(boolean,boolean,boolean) in Interface

    private static final class Bootstrapper extends PlayerHelper.Interface implements Runnable {
> Task :app:compileZz_crosswalkDebugJavaWithJavac FAILED
                         ^
/home/runner/work/KitsuneOffline/KitsuneOffline/app/src/main/java/com/silica/kitsune/WebPlayerActivity.java:139: error: method does not override or implement a method from a supertype
        @Override
        ^
2 errors

```
I don’t know Java so you’ll have to tell me what it means, if you know it

**Comment by LiEnby** [comment]
you need to build webviewRelease, not crosswalk version

**Comment by thecoder08** [comment]
Ah ok. So I'll use `./gradlew assembleWebview` as opposed to `./gradlew build`. Alright Andoid CI/CD is now working. Just merge it in. Then I guess the mobile versions are fully done, and we can close this issue.

**Comment by LiEnby** [comment]
Change the mac build to include correct icon and build as DMG not zip

**Comment by thecoder08** [comment]
Ok, it's hard to make a dmg installer from Command line as you need to use the Finder to set the background. I'll figure out how.

**Comment by LiEnby** [comment]
can you do something stupid, like emulate mouse clicks?

**Comment by thecoder08** [comment]
Yes it's possible to do it using a node.js script

**Comment by LiEnby** [comment]
your actions break with the new version with /silica/ and /gstatic/ folders.

**Comment by thecoder08** [comment]
I see you've added the extra commands yourself, is it working fine now?
